# Generated by Django 4.2.7 on 2023-11-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_rename_author_post_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="author",
        ),
    ]
