# Generated by Django 4.2.7 on 2023-11-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_rename_user_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(max_length=14),
        ),
    ]
