# Generated by Django 4.2.7 on 2023-11-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_remove_post_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
